
## Dubbo 服务消费者配置
spring:
    profiles:
        active: biz
    application:
      name: winback-gateway
dubbo:
  application:
    id: winback-gateway
    name: winback-gateway
  scan:
    basePackages: com.winback.gateway
  protocol:
    port: -1
server:
  port: 7090
  context-path: /winback-gateway


