spring:
  application:
    name: demo
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crawler?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    platform: msyql
    
    #数据库连接池配置
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    
#security.basic.enabled=false
  security:
    basic:
      enabled: false

#seimi.crawler.enabled=true
#seimi.crawler.names=DefRedis,test
#seimi.crawler.enable-redisson-queue=true
##seimi.crawler.bloom-filter-expected-insertions=
##seimi.crawler.bloom-filter-false-probability=
#seimi.crawler.seimi-agent-host=47.104.174.247
#seimi.crawler.seimi-agent-port=9010

seimi:
  crawler:
    enabled: true
#    names: serviceElite
#    enable-redisson-queue: true
#    seimi-agent-host: 47.104.174.247
#    seimi-agent-port: 9010


server:
  port: 8000
